## Starts n number of instances

- name: Start {{ num_instances }} load-balanced containers
  docker_container:
    name: "container{{ item }}"
    recreate: yes
    image: slave
    command: sleep 20ms
    pull: false # Use local repository build image
    env:
      NUM_NODES: "{{ num_nodes }}"
      MONGO_URI: "{{ mongo_db_uri }}"
  with_sequence: count={{ num_instances }}
