## This playbook configures Marvin slaves for setup.

- hosts: mongoroot
  sudo: yes
  vars_files: config-vars.yml

  roles:
    - ./roles/duck-configure
    - ./roles/duck-update
    - ./roles/duck-restart
