## This playbook configures Marvin slaves for setup.

- hosts: slaves
  sudo: yes
  vars_files: config-vars.yml

  roles:
    - ./roles/slave-configure
    - ./roles/slave-update
    - ./roles/slave-restart
