# tasks file for slave-restart

- name: Start 4 load-balanced containers
  docker_container:
    name: "container{{ item }}"
    recreate: yes
    image: slave
    command: sleep 1s
    pull: false # Use local repository build image
    env:
      NUM_NODES: 20
      MONGO_URI: "{{ mongo_db_uri }}"
  with_sequence: count=4
