## This playbook configures Marvin slaves for setup.

- import_playbook: configure-base.yml

- hosts: slaves
  sudo: yes
  vars:
    git_marvin_directory: /home/slave/repos/marvin
    marvin_github_repo_url: https://github.com/laravel/laravel.git

  tasks:
    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - git
        - vim

    - name: Clone git repository
      git: >
        dest={{ git_marvin_directory }}
        repo={{ marvin_github_repo_url }}
        update=no
      sudo: yes
      sudo_user: www-data

    - name: build the image
      docker_image: >
        name=slave
        tag=1.0.0
        path={{ git_marvin_directory }}
        state=present

    handlers:
      ---

